name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types: [completed]
    branches: [main, dev, qa]

jobs:
  terraform-apply:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Plan Artifact
        uses: actions/github-script@v7
        with:
          script: |
            // ... artifact download script from previous examples
            
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::596122389379:role/github-action-role
          aws-region: us-east-1
          
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan