name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

env:
  TF_CLI_ARGS: "-no-color"
  TF_IN_AUTOMATION: true
  AWS_REGION: us-east-1
  TRIGGER_BRANCH: ${{ github.event.workflow_run.head_branch }}   # branch that triggered the plan workflow

jobs:
  terraform-apply:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-${{ env.TRIGGER_BRANCH }}   # match artifact name from plan workflow
          path: .   # download into the workspace

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Apply (use the downloaded plan file)
        run: |
          echo "Trigger branch: ${{ env.TRIGGER_BRANCH }}"
          # find the tfplan file (downloaded artifact will place it into a folder)
          TFPLAN_PATH=$(find . -type f -name tfplan -print -quit)
          if [ -z "$TFPLAN_PATH" ]; then
            echo "tfplan file not found. Failing."
            exit 1
          fi
          echo "Found plan at: $TFPLAN_PATH"
          terraform init -input=false
          terraform apply -auto-approve -input=false "$TFPLAN_PATH"
