name: Terraform Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

env:
  TF_CLI_ARGS: "-no-color"
  TF_IN_AUTOMATION: true
  AWS_REGION: us-east-1    # <-- change this to your preferred region

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .  # <-- change if your code is elsewhere

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::596122389379:role/github-action-role
          aws-region: ${{ env.AWS_REGION }}

      # Optional: Format Check
      # - name: Terraform Format Check
      #   run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -input=false -var-file="./env/dev.tfvars"

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan


      - name: Terraform Apply (on main only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false tfplan
      - name: Show current directory and files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -al

      - name: Upload Terraform State to S3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Uploading Terraform state file to S3..."
          aws s3 cp ./terraform.tfstate s3://host-1b/terraform.tfstate

                
