name: Terraform Plan

on:
  push:
    branches:
      - main
      - dev
      - qa
      - prod
      - test

  pull_request:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

env:
  TF_CLI_ARGS: "-no-color"
  TF_IN_AUTOMATION: true
  AWS_REGION: us-east-1    # <-- change this to your preferred region

jobs:
  terraform:
    working_directory: ./terraform_module
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::596122389379:role/github-action-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Copy Environment Files
      run: |
        echo "Current directory: $(pwd)"
        echo "Branch: ${{ github.ref_name }}"
        cp ../env/${{ github.ref_name }}.tfvars ./
        ls -la

    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      if: github.ref != 'refs/heads/test' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prod')
      id: plan
      run: |
        echo "Running Terraform Plan for branch: ${GITHUB_REF#refs/heads/}"
        BRANCH="${GITHUB_REF#refs/heads/}"
        
        if [ "$BRANCH" = "dev" ]; then
          terraform plan -out=tfplan -input=false -var-file="dev.tfvars"
        elif [ "$BRANCH" = "qa" ]; then
          terraform plan -out=tfplan -input=false -var-file="qa.tfvars"
        elif [ "$BRANCH" = "main" ] || [ "$BRANCH" = "prod" ]; then
          terraform plan -out=tfplan -input=false -var-file="prod.tfvars"
        else
          echo "No specific configuration for branch: $BRANCH"
          exit 1
        fi

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-${{ github.ref_name }}
        path: terraform_module/tfplan