name: Terraform CI/CD

on:
  push:
    branches: [main, dev, qa, prod]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  TF_CLI_ARGS: "-no-color"
  TF_IN_AUTOMATION: true
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Initialize and Validate
        run: |
          terraform init -input=false
          terraform validate

      - name: Generate Terraform Plan
        id: plan
        run: |
          case "$BRANCH" in
            dev)   VARFILE="./env/dev.tfvars" ;;
            qa)    VARFILE="./env/qa.tfvars" ;;
            main)  VARFILE="./env/prod.tfvars" ;;
            prod)  VARFILE="./env/prod.tfvars" ;;
            *)     echo "Unsupported branch"; exit 1 ;;
          esac
          terraform plan -out=tfplan -input=false -var-file="$VARFILE"

      - name: Apply Terraform Plan
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -input=false tfplan