name: Terraform CI/CD

on:
  push:
    branches: [main, dev, qa, prod]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  TF_CLI_ARGS: "-no-color"
  TF_IN_AUTOMATION: true
  TF_BACKEND_BUCKET: statesotre
  TF_BACKEND_KEY: vpc.tfstate
  AWS_REGION: ap-south-1

jobs:
  terraform:
    name: Terraform Plan 
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: import_resources
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="key=${{ env.TF_BACKEND_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="encrypt=true"

      - name: Terraform Import S3 Bucket
        working-directory: import_resources
        run: terraform import aws_s3_bucket.s3_import import-s3yml


      - name: Terraform Import existing resources
        working-directory: import_resources
        run: |
          if [ -f imports.txt ]; then
            while read -r addr id || [ -n "$addr" ]; do
              echo "Importing $addr -> $id"
              terraform import -lock=false -input=false "$addr" "$id" || true
            done < imports.txt
          else
            echo "No imports.txt found, skipping import step."
          fi


      - name: Generate Terraform Plan
        working-directory: import_resources
        id: plan
        run: |
          case "$BRANCH" in
            dev)   VARFILE="./env/dev.tfvars" ;;
            qa)    VARFILE="./env/qa.tfvars" ;;
            main)  VARFILE="./env/prod.tfvars" ;;
            prod)  VARFILE="./env/prod.tfvars" ;;
            *)     echo "Unsupported branch"; exit 1 ;;
          esac
          terraform plan -out=tfplan -input=false -var-file="$VARFILE"

      # # - name: Terraform Apply
      # #   if: github.event_name == 'push'
      # #   run: terraform apply -auto-approve input=false tfplan-


      # - name: Terraform Destroy
      #   if: github.event_name == 'push'
      #   run:  terraform destroy -auto-approve -var-file="env/dev.tfvars"
       
